###
POST http://localhost:7777/love
Content-Type: application/json

{
    "id": 1,
    "message": "I love you",
    "present": {
      "id": 17,
      "matter": "Magic box",
      "description": "Announce of loving",
      "bestBefore": "03/25"
    }
}

###
POST http://localhost:7777/plainlove
Content-Type: application/json

{
    "id": 1,
    "message": "I love you"
}